# Generated by Django 4.2.7 on 2023-12-28 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chirps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirpevent",
            name="webhook_payload",
            field=models.TextField(default=""),
        ),
    ]
