# Generated by Django 4.2.7 on 2023-12-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chirps", "0002_chirpevent_webhook_payload"),
    ]

    operations = [
        migrations.AddField(
            model_name="chirp",
            name="level",
            field=models.CharField(default="yellow"),
        ),
    ]
