# Generated by Django 4.2.7 on 2023-12-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chirps", "0003_chirp_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chirp",
            name="token",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
